name: Basic CI Pipeline
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run echo command
        run: echo "CI Pipeline Executed Successfully"

      - name: Run health check
        run: ./scripts/health.sh
